//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public int AccountType { get; set; }
        public int EmployeeId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string ActivateCode { get; set; }
        public string Coso { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Level Level { get; set; }
    }
}
