//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLevelPermission
    {
        public int AdminLevelId { get; set; }
        public string TableName { get; set; }
        public int Permission { get; set; }
    
        public virtual AdminLevel AdminLevel { get; set; }
    }
}
