//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumPicture
    {
        public int Id { get; set; }
        public string PictureName { get; set; }
        public int AlbumId { get; set; }
        public string ten { get; set; }
        public string mota { get; set; }
        public Nullable<int> chucvuId { get; set; }
    
        public virtual DM_Chucvus DM_Chucvus { get; set; }
    }
}
