//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_LoaiThietBi()
        {
            this.DM_ThietBi = new HashSet<DM_ThietBi>();
        }
    
        public int Loaithietbi_Id { get; set; }
        public string Ma_Loai { get; set; }
        public string Ten_Loai { get; set; }
        public string Mo_Ta { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
        public Nullable<int> Donvi_Id { get; set; }
    
        public virtual DM_DonVis DM_DonVis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_ThietBi> DM_ThietBi { get; set; }
    }
}
