//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_ThietBi()
        {
            this.ThietBi_ChiTiet = new HashSet<ThietBi_ChiTiet>();
            this.ThietBi_DonVi = new HashSet<ThietBi_DonVi>();
            this.HoSoPhapLys = new HashSet<HoSoPhapLy>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public int DonVi_Id { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> LoaiThietBi_id { get; set; }
        public string BienSo { get; set; }
        public string NhanHieu { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string NamSanXuat { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> NguoiSuDung_Id { get; set; }
        public string TinhTrangKyThuat { get; set; }
        public Nullable<int> HoSoPhapLy_Id { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ThongSoKyThuat { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiCapNhat_Id { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public string IP { get; set; }
        public Nullable<int> TinhTrang_Id { get; set; }
        public Nullable<int> PhongBan_Id { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau_su_dung { get; set; }
        public Nullable<System.DateTime> ngay_bao_tri_cuoi { get; set; }
        public Nullable<System.DateTime> ngay_bao_tri_tiep_theo { get; set; }
        public string MaSoRieng { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual DM_LoaiThietBi DM_LoaiThietBi { get; set; }
        public virtual DM_PhongBans DM_PhongBans { get; set; }
        public virtual HoSoPhapLy HoSoPhapLy { get; set; }
        public virtual StatusProject StatusProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThietBi_ChiTiet> ThietBi_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThietBi_DonVi> ThietBi_DonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoPhapLy> HoSoPhapLys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
