//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> LevelId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> KhoaphongId { get; set; }
        public Nullable<int> KhoaChuyenId { get; set; }
        public Nullable<int> NghenghiepId { get; set; }
        public Nullable<int> ChucvuId { get; set; }
        public Nullable<int> HocviId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CityId { get; set; }
        public string DistrictId { get; set; }
        public string WardId { get; set; }
        public string Avatar { get; set; }
        public int Gender { get; set; }
        public string Birthday { get; set; }
        public bool TrangThaiChuyen { get; set; }
        public Nullable<bool> Canhan { get; set; }
        public bool Import { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual DM_Chucvus DM_Chucvus { get; set; }
        public virtual DM_Donvihanhchinhs DM_Donvihanhchinhs { get; set; }
        public virtual DM_Hocvis DM_Hocvis { get; set; }
        public virtual DM_Nghenghieps DM_Nghenghieps { get; set; }
        public virtual DM_PhongBans DM_PhongBans { get; set; }
        public virtual DM_PhongBans DM_PhongBans1 { get; set; }
        public virtual Level Level { get; set; }
    }
}
