//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDongNhanSu
    {
        public int Id { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<int> NguoiTruc_Id { get; set; }
        public Nullable<decimal> TongNhanSu { get; set; }
        public Nullable<decimal> CongTac { get; set; }
        public Nullable<decimal> NghiPhep { get; set; }
        public Nullable<decimal> DiHoc { get; set; }
        public Nullable<decimal> LyDoKhac { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Note { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
