//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoPhapLy
    {
        public int Id { get; set; }
        public string STT { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string TenHoSo { get; set; }
        public Nullable<int> AddBangId { get; set; }
        public string Url { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string Note { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual DM_AddBangs DM_AddBangs { get; set; }
        public virtual Project Project { get; set; }
    }
}
