//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoPhapLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoSoPhapLy()
        {
            this.DM_ThietBi = new HashSet<DM_ThietBi>();
        }
    
        public int Id { get; set; }
        public string STT { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string TenHoSo { get; set; }
        public Nullable<int> AddBangId { get; set; }
        public string Url { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string Note { get; set; }
        public Nullable<int> DonVi_Id { get; set; }
        public Nullable<int> NhapBanMu_Id { get; set; }
        public Nullable<int> ThietBi_Id { get; set; }
        public Nullable<int> XayDung_Id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DM_AddBangs DM_AddBangs { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Project Project { get; set; }
        public virtual NhapBanMu NhapBanMu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_ThietBi> DM_ThietBi { get; set; }
        public virtual DM_ThietBi DM_ThietBi1 { get; set; }
    }
}
