//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_DoiPhong
    {
        public int Id { get; set; }
        public int DatPhongId { get; set; }
        public int PhongCuId { get; set; }
        public int PhongMoiId { get; set; }
        public decimal GiaPhongCu { get; set; }
        public decimal GiaPhongMoi { get; set; }
        public string LyDo { get; set; }
        public int NguoiDoiId { get; set; }
        public System.DateTime ThoiGianDoi { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual KhachSan_DatPhong KhachSan_DatPhong { get; set; }
        public virtual KhachSan_Phong KhachSan_Phong { get; set; }
        public virtual KhachSan_Phong KhachSan_Phong1 { get; set; }
    }
}
