//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_LoaiPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan_LoaiPhong()
        {
            this.KhachSan_Phong = new HashSet<KhachSan_Phong>();
        }
    
        public int Id { get; set; }
        public string TenLoai { get; set; }
        public decimal GiaGioNgan { get; set; }
        public decimal GiaQuaDem { get; set; }
        public decimal GiaTheoNgay { get; set; }
        public int SoNguoiToiDa { get; set; }
        public string MoTa { get; set; }
        public int DonViId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual DM_DonVis DM_DonVis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_Phong> KhachSan_Phong { get; set; }
    }
}
