//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_DichVuPhuThu
    {
        public int Id { get; set; }
        public int DatPhongId { get; set; }
        public string TenDichVu { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
        public System.DateTime NgayPhatSinh { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual KhachSan_DatPhong KhachSan_DatPhong { get; set; }
    }
}
