//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_TrangThaiLichSu
    {
        public int Id { get; set; }
        public int PhongId { get; set; }
        public int TrangThaiCu { get; set; }
        public int TrangThaiMoi { get; set; }
        public int NguoiThayDoiId { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual KhachSan_Phong KhachSan_Phong { get; set; }
    }
}
