//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan_DatPhong()
        {
            this.KhachSan_DichVuPhuThu = new HashSet<KhachSan_DichVuPhuThu>();
            this.KhachSan_DoiPhong = new HashSet<KhachSan_DoiPhong>();
            this.KhachSan_KiemPhong = new HashSet<KhachSan_KiemPhong>();
            this.KhachSan_ThanhToan = new HashSet<KhachSan_ThanhToan>();
        }
    
        public int Id { get; set; }
        public string MaPhieu { get; set; }
        public int PhongId { get; set; }
        public int KhachHangId { get; set; }
        public Nullable<int> NhanVienCheckInId { get; set; }
        public Nullable<int> NhanVienCheckOutId { get; set; }
        public System.DateTime ThoiGianCheckIn { get; set; }
        public Nullable<System.DateTime> ThoiGianCheckOutDuKien { get; set; }
        public Nullable<System.DateTime> ThoiGianCheckOutThucTe { get; set; }
        public int LoaiGia { get; set; }
        public int SoNguoi { get; set; }
        public decimal TienPhong { get; set; }
        public decimal TienPhuThu { get; set; }
        public decimal TienGiamGia { get; set; }
        public decimal TongTien { get; set; }
        public decimal DaThanhToan { get; set; }
        public int TrangThai { get; set; }
        public int NguonBooking { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<int> NguoiHuyId { get; set; }
        public Nullable<System.DateTime> ThoiGianHuy { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual KhachSan_KhachHang KhachSan_KhachHang { get; set; }
        public virtual KhachSan_Phong KhachSan_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_DichVuPhuThu> KhachSan_DichVuPhuThu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_DoiPhong> KhachSan_DoiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_KiemPhong> KhachSan_KiemPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_ThanhToan> KhachSan_ThanhToan { get; set; }
    }
}
