//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_KiemPhong
    {
        public int Id { get; set; }
        public int DatPhongId { get; set; }
        public int PhongId { get; set; }
        public int NhanVienKiemId { get; set; }
        public System.DateTime ThoiGianKiem { get; set; }
        public int TrangThai { get; set; }
        public decimal PhiMinibar { get; set; }
        public decimal PhiHuHong { get; set; }
        public decimal PhiMatDo { get; set; }
        public decimal PhiVeSinh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual KhachSan_DatPhong KhachSan_DatPhong { get; set; }
        public virtual KhachSan_Phong KhachSan_Phong { get; set; }
    }
}
