//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_ThanhToan
    {
        public int Id { get; set; }
        public int DatPhongId { get; set; }
        public decimal SoTien { get; set; }
        public int HinhThuc { get; set; }
        public int LoaiThu { get; set; }
        public string MaGiaoDich { get; set; }
        public int NguoiThuId { get; set; }
        public System.DateTime NgayThu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual KhachSan_DatPhong KhachSan_DatPhong { get; set; }
    }
}
