//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan_Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan_Phong()
        {
            this.KhachSan_DatPhong = new HashSet<KhachSan_DatPhong>();
            this.KhachSan_DoiPhong = new HashSet<KhachSan_DoiPhong>();
            this.KhachSan_DoiPhong1 = new HashSet<KhachSan_DoiPhong>();
            this.KhachSan_KiemPhong = new HashSet<KhachSan_KiemPhong>();
            this.KhachSan_TrangThaiLichSu = new HashSet<KhachSan_TrangThaiLichSu>();
        }
    
        public int Id { get; set; }
        public string SoPhong { get; set; }
        public string TenPhong { get; set; }
        public int LoaiPhongId { get; set; }
        public int DonViId { get; set; }
        public Nullable<int> Tang { get; set; }
        public int TrangThai { get; set; }
        public string MoTa { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DM_DonVis DM_DonVis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_DatPhong> KhachSan_DatPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_DoiPhong> KhachSan_DoiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_DoiPhong> KhachSan_DoiPhong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_KiemPhong> KhachSan_KiemPhong { get; set; }
        public virtual KhachSan_LoaiPhong KhachSan_LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachSan_TrangThaiLichSu> KhachSan_TrangThaiLichSu { get; set; }
    }
}
