//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhaoSat
    {
        public int Id { get; set; }
        public Nullable<int> DonViKhaoSatId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<decimal> GiaTriHopDong { get; set; }
        public Nullable<decimal> GiaTriPLHopDong { get; set; }
        public Nullable<decimal> LandArea { get; set; }
        public Nullable<decimal> WaterArea { get; set; }
        public Nullable<decimal> LandAreaKhaoSat { get; set; }
        public Nullable<decimal> WaterAreaKhaoSat { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> GiaTriThamDinh { get; set; }
        public Nullable<decimal> GiaTriDuToan { get; set; }
        public Nullable<decimal> GiaTriKhaoSat { get; set; }
        public Nullable<decimal> GiaTriDuToanPheDuyet { get; set; }
        public Nullable<decimal> GiaTriKhaoSatPheDuyet { get; set; }
        public Nullable<decimal> GiaTriThamDinhPheDuyet { get; set; }
        public string KetQuaKhaoSat { get; set; }
        public Nullable<decimal> ChiPhiGiamSat { get; set; }
        public string NguoiGiamSat { get; set; }
        public Nullable<int> TinhTrangDuAn { get; set; }
        public bool TinhTrangCongNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string Note { get; set; }
        public string SoPLHD { get; set; }
        public Nullable<decimal> CongNo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual StatusProject StatusProject { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Project Project { get; set; }
    }
}
