//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuuVet
    {
        public int Id { get; set; }
        public Nullable<int> IdApi { get; set; }
        public Nullable<int> EmployeeCheckinId { get; set; }
        public Nullable<int> KhoaCheckinId { get; set; }
        public string thoiGianCheckin { get; set; }
        public Nullable<int> KhuPhanLuongId { get; set; }
        public string ticketNumber { get; set; }
        public string qrQgCode { get; set; }
        public string qrQgCode2 { get; set; }
    }
}
