//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaQuocGia
    {
        public int Id { get; set; }
        public string Ma { get; set; }
        public string idQuocgia { get; set; }
        public string ten { get; set; }
    }
}
