//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class namlao206_websiteEntities : DbContext
    {
        public namlao206_websiteEntities()
            : base("name=namlao206_websiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<AdminLevelPermission> AdminLevelPermissions { get; set; }
        public virtual DbSet<AdminLevel> AdminLevels { get; set; }
        public virtual DbSet<AlbumPicture> AlbumPictures { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<CalrouselPicture> CalrouselPictures { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DM_AddBangs> DM_AddBangs { get; set; }
        public virtual DbSet<DM_Chucvus> DM_Chucvus { get; set; }
        public virtual DbSet<DM_Donvihanhchinhs> DM_Donvihanhchinhs { get; set; }
        public virtual DbSet<DM_DonVis> DM_DonVis { get; set; }
        public virtual DbSet<DM_hinhthuckinhdoanh> DM_hinhthuckinhdoanh { get; set; }
        public virtual DbSet<DM_Hocvis> DM_Hocvis { get; set; }
        public virtual DbSet<DM_Nghenghieps> DM_Nghenghieps { get; set; }
        public virtual DbSet<DM_NhomPhongBans> DM_NhomPhongBans { get; set; }
        public virtual DbSet<DM_PhongBans> DM_PhongBans { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GiamSatThiCong> GiamSatThiCongs { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<HoatDongNhanSu> HoatDongNhanSus { get; set; }
        public virtual DbSet<HoSoPhapLy> HoSoPhapLys { get; set; }
        public virtual DbSet<KhaoSat> KhaoSats { get; set; }
        public virtual DbSet<LevelPermission> LevelPermissions { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LuuVet> LuuVets { get; set; }
        public virtual DbSet<MaQuocGia> MaQuocGias { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsPicture> NewsPictures { get; set; }
        public virtual DbSet<NghiemThu> NghiemThus { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<StatusProject> StatusProjects { get; set; }
        public virtual DbSet<StorageFile> StorageFiles { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<ThiCong> ThiCongs { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TransportFile> TransportFiles { get; set; }
        public virtual DbSet<TransportFileUrl> TransportFileUrls { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserPermissionGroup> UserPermissionGroups { get; set; }
        public virtual DbSet<PermissionGroup> PermissionGroups { get; set; }
        public virtual DbSet<DM_AdminListUpItem> DM_AdminListUpItem { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<NhapBanMu> NhapBanMus { get; set; }
        public virtual DbSet<TonKho> TonKhoes { get; set; }
        public virtual DbSet<DM_LoaiThietBi> DM_LoaiThietBi { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<ThietBi_DonVi> ThietBi_DonVi { get; set; }
        public virtual DbSet<ThietBi_LichSu> ThietBi_LichSu { get; set; }
        public virtual DbSet<DM_ThietBi> DM_ThietBi { get; set; }
        public virtual DbSet<ThietBi_ChiTiet> ThietBi_ChiTiet { get; set; }
        public virtual DbSet<KhachSan_DatPhong> KhachSan_DatPhong { get; set; }
        public virtual DbSet<KhachSan_DichVuPhuThu> KhachSan_DichVuPhuThu { get; set; }
        public virtual DbSet<KhachSan_DoiPhong> KhachSan_DoiPhong { get; set; }
        public virtual DbSet<KhachSan_KhachHang> KhachSan_KhachHang { get; set; }
        public virtual DbSet<KhachSan_KiemPhong> KhachSan_KiemPhong { get; set; }
        public virtual DbSet<KhachSan_LoaiPhong> KhachSan_LoaiPhong { get; set; }
        public virtual DbSet<KhachSan_Phong> KhachSan_Phong { get; set; }
        public virtual DbSet<KhachSan_ThanhToan> KhachSan_ThanhToan { get; set; }
        public virtual DbSet<KhachSan_TrangThaiLichSu> KhachSan_TrangThaiLichSu { get; set; }
    
        public virtual ObjectResult<sp_GetDataForDashBoard_Result> sp_GetDataForDashBoard(string action, string fromDate, string toDate, Nullable<int> donvi_id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var donvi_idParameter = donvi_id.HasValue ?
                new ObjectParameter("Donvi_id", donvi_id) :
                new ObjectParameter("Donvi_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDataForDashBoard_Result>("sp_GetDataForDashBoard", actionParameter, fromDateParameter, toDateParameter, donvi_idParameter);
        }
    
        public virtual int sp_CapNhatSoLuongThietBi(Nullable<int> thietbi_id, Nullable<int> donvi_id, Nullable<int> phongban_id, Nullable<decimal> so_luong_moi, string loai_thay_doi, Nullable<int> nguoi_thay_doi, string ly_do, Nullable<int> nguoiTao_Id, Nullable<int> nguoiCapNhat_Id)
        {
            var thietbi_idParameter = thietbi_id.HasValue ?
                new ObjectParameter("thietbi_id", thietbi_id) :
                new ObjectParameter("thietbi_id", typeof(int));
    
            var donvi_idParameter = donvi_id.HasValue ?
                new ObjectParameter("donvi_id", donvi_id) :
                new ObjectParameter("donvi_id", typeof(int));
    
            var phongban_idParameter = phongban_id.HasValue ?
                new ObjectParameter("phongban_id", phongban_id) :
                new ObjectParameter("phongban_id", typeof(int));
    
            var so_luong_moiParameter = so_luong_moi.HasValue ?
                new ObjectParameter("so_luong_moi", so_luong_moi) :
                new ObjectParameter("so_luong_moi", typeof(decimal));
    
            var loai_thay_doiParameter = loai_thay_doi != null ?
                new ObjectParameter("loai_thay_doi", loai_thay_doi) :
                new ObjectParameter("loai_thay_doi", typeof(string));
    
            var nguoi_thay_doiParameter = nguoi_thay_doi.HasValue ?
                new ObjectParameter("nguoi_thay_doi", nguoi_thay_doi) :
                new ObjectParameter("nguoi_thay_doi", typeof(int));
    
            var ly_doParameter = ly_do != null ?
                new ObjectParameter("ly_do", ly_do) :
                new ObjectParameter("ly_do", typeof(string));
    
            var nguoiTao_IdParameter = nguoiTao_Id.HasValue ?
                new ObjectParameter("NguoiTao_Id", nguoiTao_Id) :
                new ObjectParameter("NguoiTao_Id", typeof(int));
    
            var nguoiCapNhat_IdParameter = nguoiCapNhat_Id.HasValue ?
                new ObjectParameter("NguoiCapNhat_Id", nguoiCapNhat_Id) :
                new ObjectParameter("NguoiCapNhat_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatSoLuongThietBi", thietbi_idParameter, donvi_idParameter, phongban_idParameter, so_luong_moiParameter, loai_thay_doiParameter, nguoi_thay_doiParameter, ly_doParameter, nguoiTao_IdParameter, nguoiCapNhat_IdParameter);
        }
    }
}
