//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class namlao206dbEntities : DbContext
    {
        public namlao206dbEntities()
            : base("name=namlao206dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<AdminLevelPermission> AdminLevelPermissions { get; set; }
        public virtual DbSet<AdminLevel> AdminLevels { get; set; }
        public virtual DbSet<AlbumPicture> AlbumPictures { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<CalrouselPicture> CalrouselPictures { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DM_AdminListUpItem> DM_AdminListUpItem { get; set; }
        public virtual DbSet<DM_Chucvus> DM_Chucvus { get; set; }
        public virtual DbSet<DM_Donvihanhchinhs> DM_Donvihanhchinhs { get; set; }
        public virtual DbSet<DM_DonVis> DM_DonVis { get; set; }
        public virtual DbSet<DM_hinhthuckinhdoanh> DM_hinhthuckinhdoanh { get; set; }
        public virtual DbSet<DM_Hocvis> DM_Hocvis { get; set; }
        public virtual DbSet<DM_Nghenghieps> DM_Nghenghieps { get; set; }
        public virtual DbSet<DM_NhomPhongBans> DM_NhomPhongBans { get; set; }
        public virtual DbSet<DM_PhongBans> DM_PhongBans { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<LevelPermission> LevelPermissions { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LuuVet> LuuVets { get; set; }
        public virtual DbSet<MaQuocGia> MaQuocGias { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<NewsPicture> NewsPictures { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TransportFileUrl> TransportFileUrls { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<TransportFile> TransportFiles { get; set; }
    }
}
