//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapBanMu
    {
        public int Id { get; set; }
        public Nullable<int> DonVi_Id { get; set; }
        public string MaPhieu { get; set; }
        public string TenPhieu { get; set; }
        public Nullable<int> Team_Id { get; set; }
        public string LoaiMu { get; set; }
        public Nullable<int> NguoiNhap_ACC_Id { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> NguoiPheDuyet_EMP_Id { get; set; }
        public Nullable<int> TroLyKeHoach_EMP_Id { get; set; }
        public Nullable<decimal> KhoiLuongThuVao { get; set; }
        public Nullable<decimal> KhoiLuongTTTC { get; set; }
        public Nullable<decimal> KhoiLuongThuVaoLast { get; set; }
        public Nullable<decimal> KhoiLuongTTTCLast { get; set; }
        public Nullable<int> LoaiHs { get; set; }
        public Nullable<int> LoaiTK { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string Note { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> KeToan_EMP_Id { get; set; }
        public Nullable<decimal> KhoiLuongTTL { get; set; }
        public Nullable<int> DanhGiaCLMu { get; set; }
        public Nullable<int> DoiTac_Id { get; set; }
        public Nullable<int> DonViTienTe_Id { get; set; }
        public Nullable<int> NguoiCan_EMP_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ModifiedAccount_Id { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual StatusProject StatusProject { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual NhapBanMu NhapBanMu1 { get; set; }
        public virtual NhapBanMu NhapBanMu2 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Team Team { get; set; }
        public virtual StatusProject StatusProject1 { get; set; }
    }
}
