//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.GiamSatThiCongs = new HashSet<GiamSatThiCong>();
            this.HoSoPhapLys = new HashSet<HoSoPhapLy>();
            this.KhaoSats = new HashSet<KhaoSat>();
            this.NghiemThus = new HashSet<NghiemThu>();
            this.ThiCongs = new HashSet<ThiCong>();
        }
    
        public int Id { get; set; }
        public string TenDuAn { get; set; }
        public string MaDuAn { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<int> XaId { get; set; }
        public Nullable<int> HuyenId { get; set; }
        public Nullable<int> TinhId { get; set; }
        public Nullable<int> InvestorId { get; set; }
        public Nullable<decimal> ProjectValue { get; set; }
        public string GiamSat { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TinhTrangDuAn { get; set; }
        public bool TinhTrangCongNo { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Longtitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string DiaChi { get; set; }
        public Nullable<decimal> CongNo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiamSatThiCong> GiamSatThiCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoPhapLy> HoSoPhapLys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaoSat> KhaoSats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NghiemThu> NghiemThus { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual StatusProject StatusProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiCong> ThiCongs { get; set; }
    }
}
