//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageFile
    {
        public int Id { get; set; }
        public string TenFile { get; set; }
        public string LoaiFile { get; set; }
        public Nullable<int> News_Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser_Id { get; set; }
        public bool IsActive { get; set; }
        public string TenFile_Phu { get; set; }
        public string Url { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual News News { get; set; }
    }
}
