//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBiXeMay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBiXeMay()
        {
            this.HoSoPhapLys = new HashSet<HoSoPhapLy>();
        }
    
        public int Id { get; set; }
        public int DonVi_Id { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string LoaiTrangThietBi { get; set; }
        public string BienSo { get; set; }
        public string NhanHieu { get; set; }
        public string SoKhung { get; set; }
        public string SoMay { get; set; }
        public string NamSanXuat { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> NguoiSuDung_Id { get; set; }
        public string TinhTrangKyThuat { get; set; }
        public Nullable<int> HoSoPhapLy_Id { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser_Id { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DM_DonVis DM_DonVis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoPhapLy> HoSoPhapLys { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
