//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi_ChiTiet
    {
        public int ThietBi_ChiTiet_Id { get; set; }
        public int ThietBi_Id { get; set; }
        public Nullable<int> Donvi_Id { get; set; }
        public Nullable<int> Phongban_Id { get; set; }
        public string Ma_So_Rieng { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<System.DateTime> ngay_mua { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau_su_dung { get; set; }
        public Nullable<System.DateTime> ngay_bao_tri_cuoi { get; set; }
        public Nullable<System.DateTime> ngay_bao_tri_tiep_theo { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
        public Nullable<int> NguoiTao_Id { get; set; }
        public Nullable<int> NguoiCapNhat_Id { get; set; }
        public string BienSo { get; set; }
        public string SoKhung { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual DM_PhongBans DM_PhongBans { get; set; }
        public virtual DM_ThietBi DM_ThietBi { get; set; }
        public virtual StatusProject StatusProject { get; set; }
    }
}
