//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi_LichSu
    {
        public int ThietBi_LichSu_id { get; set; }
        public Nullable<int> Thietbi_Donvi_Id { get; set; }
        public Nullable<decimal> so_luong_cu { get; set; }
        public Nullable<decimal> so_luong_moi { get; set; }
        public string loai_thay_doi { get; set; }
        public Nullable<int> nguoi_thay_doi { get; set; }
        public string ly_do { get; set; }
        public Nullable<System.DateTime> ngay_thay_doi { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NguoiTao_Id { get; set; }
        public Nullable<System.DateTime> NgayTao_Id { get; set; }
        public Nullable<int> NguoiCapNhat_Id { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual ThietBi_DonVi ThietBi_DonVi { get; set; }
    }
}
