//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi_DonVi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi_DonVi()
        {
            this.ThietBi_LichSu = new HashSet<ThietBi_LichSu>();
        }
    
        public int Thietbi_Donvi_Id { get; set; }
        public int Thietbi_Id { get; set; }
        public Nullable<int> Donvi_Id { get; set; }
        public Nullable<int> Phongban_id { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> SoLuong_ThucTe { get; set; }
        public Nullable<decimal> SoLuong_Hong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao_Id { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiCapNhat_Id { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DM_DonVis DM_DonVis { get; set; }
        public virtual DM_PhongBans DM_PhongBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThietBi_LichSu> ThietBi_LichSu { get; set; }
        public virtual DM_ThietBi DM_ThietBi { get; set; }
    }
}
