//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKho
    {
        public int TonKho_Id { get; set; }
        public int DonVi_Id { get; set; }
        public int ThietBi_Id { get; set; }
        public Nullable<int> NguonNhapHang_Id { get; set; }
        public Nullable<int> SoLoNhap_Id { get; set; }
        public Nullable<decimal> DonGiaMua { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao_Id { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiCapNhat_Id { get; set; }
        public Nullable<int> FixDuocTonKho_Id { get; set; }
        public Nullable<int> FixSoloNhap_ID { get; set; }
    }
}
