//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamLao206.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportFile()
        {
            this.TransportFileUrls = new HashSet<TransportFileUrl>();
            this.Transports = new HashSet<Transport>();
        }
    
        public int Id { get; set; }
        public string tenFile { get; set; }
        public string url { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public bool IsActive { get; set; }
        public bool KhanCap { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<int> NguoiPheDuyetId { get; set; }
        public string DoMat { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportFileUrl> TransportFileUrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transports { get; set; }
    }
}
